version: "3"

tasks:
  init:
    cmds:
      - git submodule update --init --recursive
  sync:
    cmds:
      - git submodule foreach "git checkout main"
      - git submodule foreach "git pull"
  status:
    cmds:
      - git submodule status
      - git submodule foreach "git status -s -b"
  stash:
    cmds:
      - git submodule foreach "git stash save -u"
      - git submodule foreach "git status -s -b"
